security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        Appydo\TestBundle\Entity\User:
          algorithm: sha1
          encode_as_base64: false
          iterations: 300

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_db:
            entity: { class: AppydoTestBundle:User }
        #in_memory:
        #    users:
        #        user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #        admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern: ^/
            form_login:
                always_use_default_target_path: true
                default_target_path: /admin/
                check_path: /admin/login_check
                login_path: /login
            logout:
                path:   /admin/logout
                target: /
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/appydo.*, role: ROLE_USER }
        #- { path: ^/admin/user/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin.*, role: ROLE_USER }
        #- { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
